### ISSUE TITLE
Compatible with Redmine 3.4

### ISSUE THREAD

**Issue by daltinn** [KKBOX/redmine-trello-card-sync#10]
In fresh Redmine environment:
```
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.2.6-p396 (2016-11-15) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  no plugin installed
```

After install plugin & configure API key  & member token experience "Internal error"
production log:
```
Started GET "/admin/plugins" for 192.168.1.171 at 2017-07-21 16:55:05 +0300
Processing by AdminController#plugins as HTML
  Current user: admin (id=1)
  Rendered admin/plugins.html.erb within layouts/admin (0.8ms)
  Rendered admin/_menu.html.erb (2.9ms)
  Rendered layouts/base.html.erb (3.6ms)
Completed 500 Internal Server Error in 13ms (ActiveRecord: 1.4ms)

ActionView::Template::Error (undefined method `strip' for nil:NilClass):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: <!-- page specific tags -->
    18: <%= yield :header_tags -%>
    19: </head>
  plugins/redmine_trello_card_sync/lib/redmine_trello_card_sync/hooks.rb:9:in `block in initialize'
  plugins/redmine_trello_card_sync/lib/redmine_trello_card_sync/hooks.rb:8:in `initialize'
  lib/redmine/hook.rb:35:in `block in listeners'
  lib/redmine/hook.rb:35:in `collect'
  lib/redmine/hook.rb:35:in `listeners'
  lib/redmine/hook.rb:40:in `hook_listeners'
  lib/redmine/hook.rb:59:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb___4542969176980208725_36321780'
  app/views/layouts/admin.html.erb:8:in `_app_views_layouts_admin_html_erb__651210782668257471_35987620'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by hiroshiyui** [comment]
@daltinn Please give the latest release a try.

**Comment by hiroshiyui** [comment]
@daltinn Sorry, I forget to push the updated code here, if you are confused with it, please git pull this again.

**Comment by daltinn** [comment]
Thank you! Problem fixed.

As I see, this plugin provide one way  sync, right? 
Do you have plan for two way sync?

**Comment by hiroshiyui** [comment]
@daltinn Yes, bidirectional synchronization is WIP, you may subscribe #11 for the progress update, though the priority is not too high.

**Comment by daltinn** [comment]
Thank you!
