### ISSUE TITLE
Error 500 when loading mu account page

### ISSUE THREAD

**Issue by humbertofraga** [KKBOX/redmine-trello-card-sync#22]
I've just installed the plugin. I did the initial configuration described on the README, but when I access my account page the following error is displayed on production.log:

```
Started GET "/my/account" for 10.1.4.20 at 2018-08-29 13:00:16 +0000
Processing by MyController#account as HTML
  Current user: humberto.fraga (id=7)
  Rendered plugins/redmine_trello_card_sync/app/views/users/_redmine_trello_card_sync.html.erb (17.7ms)
  Rendered my/account.html.erb within layouts/base (24.2ms)
Completed 500 Internal Server Error in 34ms (ActiveRecord: 3.9ms)

ActionView::Template::Error (undefined method `trello_username' for #<User:0x00007fda78059330>):
    1: <p>
    2:   <%= form.text_field :trello_username, :autocomplete => :off %>
    3: </p>
  lib/redmine/views/labelled_form_builder.rb:31:in `text_field'
  plugins/redmine_trello_card_sync/app/views/users/_redmine_trello_card_sync.html.erb:2:in `_plugins_redmine_trello_card_sync_app_views_users__redmine_trello_card_sync_html_erb___2953128170568797004_70288200410920'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/my/account.html.erb:34:in `block in _app_views_my_account_html_erb__4187287449770789451_70288199665000'
  app/helpers/application_helper.rb:1190:in `labelled_form_for'
  app/views/my/account.html.erb:14:in `_app_views_my_account_html_erb__4187287449770789451_70288199665000'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by humbertofraga** [comment]
The problem was that I skipped the migrate_plugins command.
